#!/bin/sh
# /usr/local/sbin/dphys-config-alternatives - set desired /etc/alternatives/*
# author Neil Franklin, last modification 2006.08.11
# copyright ETH Zuerich Physics Departement,
#   use under either modified/non-advertising BSD or GPL license

# this script is called by dphys-config, once on each install/update
#   no parameters or env vars for this script
# it requires in /etc/dphys-config.list 1 line:
#   local/sbin/dphys-config-alternatives:/usr/:/bin/chmod 755 {}; {}


set -e

# get ready to work
PATH=/sbin:/bin:/usr/sbin:/usr/bin
export PATH


# --- window manager section

if [ -x /usr/bin/fvwm2 ]; then

  # this block taken from old /usr/sbin/dphys-local-x package
  #   possibly /usr/bin/fvwm forgets (or once forgot?) to install itsself here
  if ! /usr/sbin/update-alternatives --display x-session-manager | \
      /bin/grep -q /usr/bin/fvwm > /dev/null ; then
    /usr/sbin/update-alternatives --install /usr/bin/x-session-manager \
        x-session-manager /usr/bin/fvwm2 99 --slave \
        /usr/share/man/man1/x-session-manager.1.gz \
        x-session-manager.1.gz /usr/share/man/man1/fvwm2.1.gz
  fi

  # this added, analog to all further down
  /usr/sbin/update-alternatives --set x-session-manager /usr/bin/fvwm2

else

  # we are doing new installation, dphys-config run before dphys-admin
  #   config files + scripts are being installed, but packaged software missing
  MISSING_PACKAGE=yes

fi


# --- cursors section

if [ -f /etc/X11/cursors/core.theme ]; then

 /usr/sbin/update-alternatives --set x-cursor-theme /etc/X11/cursors/core.theme

else

  MISSING_PACKAGE=yes

fi


# --- uxterm section

if [ -x /usr/X11R6/bin/uxterm ]; then

  /usr/sbin/update-alternatives --set x-terminal-emulator /usr/X11R6/bin/uxterm
  #/usr/sbin/update-alternatives --list x-terminal-emulator | /usr/bin/nl | \
  #    /bin/grep /uxterm | /usr/bin/awk '{print $1}' | \
  #    /usr/sbin/update-alternatives --config x-terminal-emulator > /dev/null

else

  MISSING_PACKAGE=yes

fi


# --- mozilla-firefox section

if [ -x /usr/bin/mozilla-firefox ]; then

  /usr/sbin/update-alternatives --set x-www-browser /usr/bin/mozilla-firefox
  #/usr/sbin/update-alternatives --list x-www-browser | /usr/bin/nl | \
  #    /bin/grep firefox | /usr/bin/awk '{print $1}' | \
  #    /usr/sbin/update-alternatives --config x-www-browser > /dev/null

else

  MISSING_PACKAGE=yes

fi


# --- avoid problem with not running on install, because packages not yet here

if [ x${MISSING_PACKAGE} = xyes ] ; then

  # remove this script to force rerun and reinstall on next dphys-config run
  #   should happen after the reboot directly after installing all packages
  /bin/rm $0
  # this will actually produce an warning from dphys-config, but  exit 0  wrong
  exit 1

fi


# --- finish off

exit 0
